let allMusic = [
    {
        name: "This God Is Too Good",
        artist: "Nathaniel",
        img: "music-2",
        scr: "music-1",
    },
    {
        name: "Lead Me To The Cross",
        artist: "Hillsong United",
        img: "music-6",
        scr: "music-2",
    },
    {
        name: "Till the stom passes by",
        artist: "Bill & Gloria",
        img: "music-3",
        scr: "music-3",
    },
    {
        name: "changing lives",
        artist: "Don_Moen ft Frank",
        img: "music-4",
        scr: "music-4",
    },
    {
        name: "If You Believe",
        artist: "Praise_Zion",
        img: "music-7",
        scr: "music-7",
    },
    {
        name: "I_Feel_The_Pool",
        artist: "Praise_Zion",
        img: "music-7",
        scr: "music-8",
    },
    {
        name: "Your Spirit",
        artist: "Tasha Cobbs",
        img: "music-8",
        scr: "music-9",
    },
    {
        name: "Life Is A Big Fight",
        artist: "Tatiana_Manaois",
        img: "music-2",
        scr: "music-10",
    },
    {
        name: "That I Could Still Go Free",
        artist: "Gift Victor",
        img: "music-4",
        scr: "music-11",
    },
    {
        name: "I_Feel_The_Pool",
        artist: "Praise_Zion",
        img: "music-7",
        scr: "music-12",
    },
    {
        name: "The_Greatest_Love_Story",
        artist: "Sis_Elizerbeth",
        img: "music-5",
        scr: "music-13",
    },
    {
        name: "The-Lord-Is-My-Shepherd",
        artist: "Godswill_Athur",
        img: "music-7",
        scr: "music-14",
    },
    {
        name: "Arise_And_Posses",
        artist: "Third Exodus Assembly",
        img: "music-1",
        scr: "music-15",
    },
    {
        name: "The-Pilgrim",
        artist: "Assembly",
        img: "music-3",
        scr: "music-16",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-3",
        scr: "music-17",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-2",
        scr: "music-18",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-6",
        scr: "music-19",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-7",
        scr: "music-20",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-1",
        scr: "music-21",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-4",
        scr: "music-23",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-1",
        scr: "music-24",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-3",
        scr: "music-24",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-7",
        scr: "music-25",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-1",
        scr: "music-26",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-5",
        scr: "music-27",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-4",
        scr: "music-28",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-6",
        scr: "music-29",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-7",
        scr: "music-30",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-1",
        scr: "music-31",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-2",
        scr: "music-32",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-3",
        scr: "music-33",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-4",
        scr: "music-34",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-5",
        scr: "music-35",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-6",
        scr: "music-36",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-8",
        scr: "music-37",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-7",
        scr: "music-38",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-6",
        scr: "music-39",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-5",
        scr: "music-40",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-4",
        scr: "music-41",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-3",
        scr: "music-42",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-2",
        scr: "music-43",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-1",
        scr: "music-44",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-8",
        scr: "music-45",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-7",
        scr: "music-46",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-6",
        scr: "music-47",
    },
    {
        name: "unknow",
        artist: "Assembly",
        img: "music-5",
        scr: "music-48",
    },
    

]